name: Daily Telegram Post

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs at 8:00 UTC daily
  workflow_dispatch:      # Allows manual trigger
  push:
    branches: [ main ]    # Triggers on push to main branch

jobs:
  post:
    runs-on: ubuntu-latest    # Using GitHub-hosted runner instead of self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run poster script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        TELEGRAM_CHANNEL_USERNAME: ${{ secrets.TELEGRAM_CHANNEL_USERNAME }}
      run: python src/main.py